# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo 'Showing directory contents'
    ls
  displayName: 'Show directory contents'

#sonarcloud prepare



- script: |
    dotnet build
  displayName: 'dotnet build'

#sonarcloud anlyze goes here

#sonarcloud publish goes here

# Want a sonar cloud analysis even if tests fail


- script: dotnet test --logger trx
  displayName: dotnet test

# the default "condition" for every step is "succeeded()" - run this step if the previous step succeeded
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

  # have the build running agent running steps publish test build logs



- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(a2152353-9b25-48cf-bad2-948e50f630f2)'
    appType: 'webApp'
    WebAppName: 'Realm-of-Games'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'